name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable pnpm
        run: |
          corepack enable
          pnpm -v || npm i -g pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build web
        run: pnpm --filter cinechat-web build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -eux
            APP_DIR=${{ secrets.APP_DIR }}
            if [ -z "$APP_DIR" ]; then echo "APP_DIR secret missing"; exit 1; fi
            # prepare dir
            if [ ! -d "$APP_DIR" ]; then mkdir -p "$APP_DIR"; fi
            if [ ! -d "$APP_DIR/.git" ]; then
              cd "$APP_DIR"
              git clone https://github.com/${{ github.repository }} .
            else
              cd "$APP_DIR"
              git fetch --depth=1 origin main
              git reset --hard origin/main
            fi
            # ensure pnpm
            command -v pnpm >/dev/null 2>&1 || npm i -g pnpm
            pnpm install --frozen-lockfile
            pnpm --filter cinechat-web build
            # restart services (support both non-templated and @root templated names)
            systemctl restart cinechat-server || systemctl restart cinechat-server@root || true
            systemctl restart cinechat-web || systemctl restart cinechat-web@root || true
